spring:
  application: csoftz-country-state
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialize: true
    schema: classpath:schema.sql
    data: classpath:data.sql
  h2:
    console:
      enabled: true

