INSERT INTO COUNTRIES (NAME) VALUES ('Country1');
INSERT INTO COUNTRIES (NAME) VALUES ('Country2');

INSERT INTO STATES (NAME, COUNTRY_ID) VALUES ('State1', 1);
INSERT INTO STATES (NAME, COUNTRY_ID) VALUES ('State2', 1);
INSERT INTO STATES (NAME, COUNTRY_ID) VALUES ('State3', 2);