CREATE TABLE COUNTRIES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE STATES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    COUNTRY_ID BIGINT,
    CONSTRAINT FK_COUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(ID)
);